package com.lzx2005.lzx2005webapi.dao;

import com.lzx2005.lzx2005webapi.model.Blog;
import com.lzx2005.lzx2005webapi.model.BlogExample;
import com.lzx2005.lzx2005webapi.model.BlogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    int countByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    int deleteByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    int deleteByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    int insert(BlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    int insertSelective(BlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    List<BlogWithBLOBs> selectByExampleWithBLOBs(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    List<Blog> selectByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    BlogWithBLOBs selectByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") BlogWithBLOBs record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") BlogWithBLOBs record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    int updateByExample(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    int updateByPrimaryKeySelective(BlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(BlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    int updateByPrimaryKey(Blog record);
}