package com.lzx2005.lzx2005webapi.model;

import java.util.Date;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blog_id
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    private Long blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.author
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.create_time
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.view
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    private Long view;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    private Long blogType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.markdown
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    private Byte markdown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.tags
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    private String tags;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_id
     *
     * @return the value of blog.blog_id
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_id
     *
     * @param blogId the value for blog.blog_id
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.author
     *
     * @return the value of blog.author
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.author
     *
     * @param author the value for blog.author
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.create_time
     *
     * @return the value of blog.create_time
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.create_time
     *
     * @param createTime the value for blog.create_time
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.view
     *
     * @return the value of blog.view
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public Long getView() {
        return view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.view
     *
     * @param view the value for blog.view
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public void setView(Long view) {
        this.view = view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_type
     *
     * @return the value of blog.blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public Long getBlogType() {
        return blogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_type
     *
     * @param blogType the value for blog.blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public void setBlogType(Long blogType) {
        this.blogType = blogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.markdown
     *
     * @return the value of blog.markdown
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public Byte getMarkdown() {
        return markdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.markdown
     *
     * @param markdown the value for blog.markdown
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public void setMarkdown(Byte markdown) {
        this.markdown = markdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.tags
     *
     * @return the value of blog.tags
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.tags
     *
     * @param tags the value for blog.tags
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }
}