package com.lzx2005.lzx2005webapi.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BlogTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public BlogTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBlogTypeIdIsNull() {
            addCriterion("blog_type_id is null");
            return (Criteria) this;
        }

        public Criteria andBlogTypeIdIsNotNull() {
            addCriterion("blog_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andBlogTypeIdEqualTo(Long value) {
            addCriterion("blog_type_id =", value, "blogTypeId");
            return (Criteria) this;
        }

        public Criteria andBlogTypeIdNotEqualTo(Long value) {
            addCriterion("blog_type_id <>", value, "blogTypeId");
            return (Criteria) this;
        }

        public Criteria andBlogTypeIdGreaterThan(Long value) {
            addCriterion("blog_type_id >", value, "blogTypeId");
            return (Criteria) this;
        }

        public Criteria andBlogTypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("blog_type_id >=", value, "blogTypeId");
            return (Criteria) this;
        }

        public Criteria andBlogTypeIdLessThan(Long value) {
            addCriterion("blog_type_id <", value, "blogTypeId");
            return (Criteria) this;
        }

        public Criteria andBlogTypeIdLessThanOrEqualTo(Long value) {
            addCriterion("blog_type_id <=", value, "blogTypeId");
            return (Criteria) this;
        }

        public Criteria andBlogTypeIdIn(List<Long> values) {
            addCriterion("blog_type_id in", values, "blogTypeId");
            return (Criteria) this;
        }

        public Criteria andBlogTypeIdNotIn(List<Long> values) {
            addCriterion("blog_type_id not in", values, "blogTypeId");
            return (Criteria) this;
        }

        public Criteria andBlogTypeIdBetween(Long value1, Long value2) {
            addCriterion("blog_type_id between", value1, value2, "blogTypeId");
            return (Criteria) this;
        }

        public Criteria andBlogTypeIdNotBetween(Long value1, Long value2) {
            addCriterion("blog_type_id not between", value1, value2, "blogTypeId");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameIsNull() {
            addCriterion("blog_type_name is null");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameIsNotNull() {
            addCriterion("blog_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameEqualTo(String value) {
            addCriterion("blog_type_name =", value, "blogTypeName");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameNotEqualTo(String value) {
            addCriterion("blog_type_name <>", value, "blogTypeName");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameGreaterThan(String value) {
            addCriterion("blog_type_name >", value, "blogTypeName");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("blog_type_name >=", value, "blogTypeName");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameLessThan(String value) {
            addCriterion("blog_type_name <", value, "blogTypeName");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameLessThanOrEqualTo(String value) {
            addCriterion("blog_type_name <=", value, "blogTypeName");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameLike(String value) {
            addCriterion("blog_type_name like", value, "blogTypeName");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameNotLike(String value) {
            addCriterion("blog_type_name not like", value, "blogTypeName");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameIn(List<String> values) {
            addCriterion("blog_type_name in", values, "blogTypeName");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameNotIn(List<String> values) {
            addCriterion("blog_type_name not in", values, "blogTypeName");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameBetween(String value1, String value2) {
            addCriterion("blog_type_name between", value1, value2, "blogTypeName");
            return (Criteria) this;
        }

        public Criteria andBlogTypeNameNotBetween(String value1, String value2) {
            addCriterion("blog_type_name not between", value1, value2, "blogTypeName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blog_type
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 19 16:13:31 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blog_type
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}