package com.lzx2005.lzx2005webapi.model;

import java.util.Date;

public class BlogType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_type.blog_type_id
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    private Long blogTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_type.blog_type_name
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    private String blogTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_type.create_time
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_type.blog_type_id
     *
     * @return the value of blog_type.blog_type_id
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public Long getBlogTypeId() {
        return blogTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_type.blog_type_id
     *
     * @param blogTypeId the value for blog_type.blog_type_id
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public void setBlogTypeId(Long blogTypeId) {
        this.blogTypeId = blogTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_type.blog_type_name
     *
     * @return the value of blog_type.blog_type_name
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public String getBlogTypeName() {
        return blogTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_type.blog_type_name
     *
     * @param blogTypeName the value for blog_type.blog_type_name
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public void setBlogTypeName(String blogTypeName) {
        this.blogTypeName = blogTypeName == null ? null : blogTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_type.create_time
     *
     * @return the value of blog_type.create_time
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_type.create_time
     *
     * @param createTime the value for blog_type.create_time
     *
     * @mbggenerated Mon Mar 19 16:13:31 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}