package com.lzx2005.lzx2005webapi.model;

public class BlogWithBLOBs extends Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.description
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.description
     *
     * @return the value of blog.description
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.description
     *
     * @param description the value for blog.description
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbggenerated Mon Mar 19 16:13:05 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}